# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Provisioning convergence + smoke over the WebUIClient.

run_bootstrap = wait_ready -> authenticate -> converge owned global filter -> converge the pasted
tool -> attach that tool to the workspace model -> smoke: the whole hardware-free provisioning act.
The admin user, filter, tool and workspace model config are DB-persisted; every rerun updates the
filter and the tool to this repo's exact bytes and idempotently converges the model's
``meta.toolIds``. The served model rides the launcher env, and the signin fallback makes reruns
idempotent (.agent/archive/m4.md provisioning contract). smoke reads back eight facts that prove
provisioning took:

- model_enumerated: the configured model id appears in GET /api/models (OPENAI_API_BASE_URL wired +
  ENABLE_OPENAI_API on);
- tool_provisioned: the pasted tool's id appears in GET /api/v1/tools/, so the artifact loaded and
  Open WebUI generated its spec (a tool whose module fails to import is rejected at write time);
- no_tool_servers: NO ``server:``-prefixed id appears in the same readback, so the pasted tool is
  the demo's ONE operation;
- model_tool_attached: the pasted tool's id appears in the workspace model's ``meta.toolIds``;
- model_tool_exclusive: that list contains ONLY the pasted tool. Existing operator-set tool ids
  remain untouched, but a persisted extra makes bootstrap fail rather than launch a second callable;
- filter_current: the stored source equals the generated filter artifact;
- filter_global_active: the filter is active and global;
- filter_exclusive: no other active filter can rewrite the verdict.

Three filter readbacks add exact generated bytes, global activation, and exclusivity; any drift
fails bootstrap closed. SmokeResult.ok = all eight held. smoke/run_bootstrap take a structural
_Provisioner (Protocol) so a test fake drives the orchestration without HTTP.
"""

from typing import Protocol

import msgspec

from webui.client import _TOOL_SERVER_ID_PREFIX, FunctionReadback
from webui.paste_in.bundle import DEMO_FILTER_ARTIFACT, DEMO_TOOL_ARTIFACT, artifact_text
from webui.paste_in.filter import FILTER_DESCRIPTION, FILTER_ID, FILTER_NAME
from webui.settings import Settings


class _Provisioner(Protocol):
    """The WebUIClient surface smoke/run_bootstrap use (structural, so a test fake satisfies it)."""

    def wait_ready(self) -> None: ...
    def authenticate(self) -> str: ...
    def ensure_global_filter(
        self,
        *,
        function_id: str,
        name: str,
        content: str,
        description: str,
    ) -> None: ...
    def ensure_tool(
        self,
        *,
        tool_id: str,
        name: str,
        content: str,
        description: str,
    ) -> None: ...
    def ensure_model_tool(self, *, model_id: str, tool_id: str) -> None: ...
    def model_ids(self) -> list[str]: ...
    def tool_ids(self) -> list[str]: ...
    def model_tool_ids(self, model_id: str) -> list[str]: ...
    def function_states(self) -> tuple[FunctionReadback, ...]: ...


class SmokeResult(msgspec.Struct, frozen=True, kw_only=True):
    """Provisioning readback ids plus eight required flags; ok = all eight held."""

    model_ids: tuple[str, ...]
    tool_ids: tuple[str, ...]
    model_tool_ids: tuple[str, ...]
    model_enumerated: bool
    tool_provisioned: bool
    no_tool_servers: bool
    model_tool_attached: bool
    model_tool_exclusive: bool
    filter_current: bool
    filter_global_active: bool
    filter_exclusive: bool

    @property
    def ok(self) -> bool:
        """Model, sole tool and sole current global filter confirmed by readback."""
        return (
            self.model_enumerated
            and self.tool_provisioned
            and self.no_tool_servers
            and self.model_tool_attached
            and self.model_tool_exclusive
            and self.filter_current
            and self.filter_global_active
            and self.filter_exclusive
        )


def smoke(client: _Provisioner, settings: Settings) -> SmokeResult:
    """Read models, tools, and all stored functions; derive the eight required flags."""
    model_ids = client.model_ids()
    tool_ids = client.tool_ids()
    model_tool_ids = client.model_tool_ids(settings.model_id)
    functions = client.function_states()
    selected = [state for state in functions if state.id == FILTER_ID]
    installed = selected[0] if len(selected) == 1 else None
    active_filters = {state.id for state in functions if state.type == "filter" and state.is_active}
    return SmokeResult(
        model_ids=tuple(model_ids),
        tool_ids=tuple(tool_ids),
        model_tool_ids=tuple(model_tool_ids),
        model_enumerated=settings.model_id in model_ids,
        tool_provisioned=settings.tool_id in tool_ids,
        no_tool_servers=not any(i.startswith(_TOOL_SERVER_ID_PREFIX) for i in tool_ids),
        model_tool_attached=settings.tool_id in model_tool_ids,
        model_tool_exclusive=model_tool_ids == [settings.tool_id],
        filter_current=installed is not None
        and installed.content == artifact_text(DEMO_FILTER_ARTIFACT),
        filter_global_active=(
            installed is not None and installed.is_active and installed.is_global
        ),
        filter_exclusive=active_filters == {FILTER_ID},
    )


def run_bootstrap(client: _Provisioner, settings: Settings) -> SmokeResult:
    """Wait, authenticate, converge the filter, tool + model attachment, then smoke every readback.

    The tool is provisioned from the COMMITTED demo artifact, generated from the sources of the
    production pair, which differs in its anchoring constant + filter inlet template alone -- the
    demo is a live test of the shared code rather than a second wiring.
    """
    client.wait_ready()
    client.authenticate()
    client.ensure_global_filter(
        function_id=FILTER_ID,
        name=FILTER_NAME,
        content=artifact_text(DEMO_FILTER_ARTIFACT),
        description=FILTER_DESCRIPTION,
    )
    client.ensure_tool(
        tool_id=settings.tool_id,
        name=settings.tool_name,
        content=artifact_text(DEMO_TOOL_ARTIFACT),
        description=settings.tool_description,
    )
    client.ensure_model_tool(model_id=settings.model_id, tool_id=settings.tool_id)
    return smoke(client, settings)
